logging:
  level:
    com:
      ssafy:
        happyhouse:
          mapper: TRACE
          util: TRACE
    root: WARN
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.bjhelper.dto
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ssafy
    url: jdbc:mysql://localhost:3306/baekjoonhelper?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssafy
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
